name: Deploy Docs

on:
  workflow_run:
    workflows:
      - "Run Tests"
    branches:
      - develop
    types: 
      - completed

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Download Poetry
        run: curl -OsSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py

      - name: Install Poetry
        run: python install-poetry.py --preview -y && export PATH=$PATH:~/.poetry/bin

      - name: Install Package
        run: poetry install

      - name: Build Docs
        run: poetry run foliant make site -p docs

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cliar-docs.mkdocs

