name: Run Tests

on:
  push:
    branches:
      - develop

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Download Poetry
        run: curl -OsSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py

      - name: Install Poetry
        run: python install-poetry.py --preview -y && export PATH=$PATH:~/.poetry/bin

      - name: Install Package
        run: poetry install

      - name: Run Tests
        run: poetry run pytest --cov=cliar

      - name: Run Test Coverage
        run: poetry run codecov

      - name: Run Linter
        run: poetry run pylint cliar

